<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'DoctrineNamespaceCacheKey%5B%5D' => 0,
'%5BApp%5CEntity%5CPersonaje%24CLASSMETADATA%5D%5B1%5D' => 1,
'%5BApp%5CEntity%5CTweet%24CLASSMETADATA%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CTweetGuardado%24CLASSMETADATA%5D%5B1%5D' => 3,
'%5BApp%5CEntity%5CUser%24CLASSMETADATA%5D%5B1%5D' => 4,

], [

0 => 'N;',
1 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'App\\Entity\\Personaje',
                ],
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Personaje',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\PersonajeRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => [
                            'fieldName' => 'id',
                            'type' => 'integer',
                            'scale' => 0,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'id' => true,
                            'columnName' => 'id',
                        ],
                        'juego' => [
                            'fieldName' => 'juego',
                            'type' => 'string',
                            'scale' => 0,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'juego',
                        ],
                        'nombre' => [
                            'fieldName' => 'nombre',
                            'type' => 'string',
                            'scale' => 0,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'nombre',
                        ],
                        'nombreCompleto' => [
                            'fieldName' => 'nombreCompleto',
                            'type' => 'string',
                            'scale' => 0,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'nombre_completo',
                        ],
                        'hashtag' => [
                            'fieldName' => 'hashtag',
                            'type' => 'string',
                            'scale' => 0,
                            'length' => 10,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'hashtag',
                        ],
                        'dificultad' => [
                            'fieldName' => 'dificultad',
                            'type' => 'integer',
                            'scale' => 0,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'dificultad',
                        ],
                        'descripcionHeader' => [
                            'fieldName' => 'descripcionHeader',
                            'type' => 'string',
                            'scale' => 0,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => true,
                            'precision' => 0,
                            'columnName' => 'descripcion_header',
                        ],
                        'descripcionBody' => [
                            'fieldName' => 'descripcionBody',
                            'type' => 'string',
                            'scale' => 0,
                            'length' => 600,
                            'unique' => false,
                            'nullable' => true,
                            'precision' => 0,
                            'columnName' => 'descripcion_body',
                        ],
                        'discord' => [
                            'fieldName' => 'discord',
                            'type' => 'string',
                            'scale' => 0,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => true,
                            'precision' => 0,
                            'columnName' => 'discord',
                        ],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'juego' => 'juego',
                        'nombre' => 'nombre',
                        'nombre_completo' => 'nombreCompleto',
                        'hashtag' => 'hashtag',
                        'dificultad' => 'dificultad',
                        'descripcion_header' => 'descripcionHeader',
                        'descripcion_body' => 'descripcionBody',
                        'discord' => 'discord',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'juego' => 'juego',
                        'nombre' => 'nombre',
                        'nombreCompleto' => 'nombre_completo',
                        'hashtag' => 'hashtag',
                        'dificultad' => 'dificultad',
                        'descripcionHeader' => 'descripcion_header',
                        'descripcionBody' => 'descripcion_body',
                        'discord' => 'discord',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'personaje',
                    ],
                ],
                'idGenerator' => [
                    $o[1],
                ],
            ],
        ],
        $o[0],
        []
    );
},
2 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'App\\Entity\\Tweet',
                ],
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Tweet',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\TweetRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => [
                            'fieldName' => 'id',
                            'type' => 'integer',
                            'scale' => 0,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'id' => true,
                            'columnName' => 'id',
                        ],
                        'juego' => [
                            'fieldName' => 'juego',
                            'type' => 'string',
                            'scale' => 0,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'juego',
                        ],
                        'hashtag' => [
                            'fieldName' => 'hashtag',
                            'type' => 'string',
                            'scale' => 0,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'hashtag',
                        ],
                        'url' => [
                            'fieldName' => 'url',
                            'type' => 'string',
                            'scale' => 0,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => true,
                            'precision' => 0,
                            'columnName' => 'url',
                        ],
                        'texto' => [
                            'fieldName' => 'texto',
                            'type' => 'string',
                            'scale' => 0,
                            'length' => 500,
                            'unique' => false,
                            'nullable' => true,
                            'precision' => 0,
                            'columnName' => 'texto',
                        ],
                        'imagen' => [
                            'fieldName' => 'imagen',
                            'type' => 'string',
                            'scale' => 0,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => true,
                            'precision' => 0,
                            'columnName' => 'imagen',
                        ],
                        'video' => [
                            'fieldName' => 'video',
                            'type' => 'string',
                            'scale' => 0,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => true,
                            'precision' => 0,
                            'columnName' => 'video',
                        ],
                        'usuario' => [
                            'fieldName' => 'usuario',
                            'type' => 'string',
                            'scale' => 0,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'usuario',
                        ],
                        'fotoUsuario' => [
                            'fieldName' => 'fotoUsuario',
                            'type' => 'string',
                            'scale' => 0,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => true,
                            'precision' => 0,
                            'columnName' => 'foto_usuario',
                        ],
                        'contgamepre' => [
                            'fieldName' => 'contgamepre',
                            'type' => 'integer',
                            'scale' => 0,
                            'length' => null,
                            'unique' => false,
                            'nullable' => true,
                            'precision' => 0,
                            'columnName' => 'contgamepre',
                        ],
                        'contgamepost' => [
                            'fieldName' => 'contgamepost',
                            'type' => 'integer',
                            'scale' => 0,
                            'length' => null,
                            'unique' => false,
                            'nullable' => true,
                            'precision' => 0,
                            'columnName' => 'contgamepost',
                        ],
                        'idTweet' => [
                            'fieldName' => 'idTweet',
                            'type' => 'string',
                            'scale' => 0,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'id_tweet',
                        ],
                        'fecha' => [
                            'fieldName' => 'fecha',
                            'type' => 'datetime',
                            'scale' => 0,
                            'length' => null,
                            'unique' => false,
                            'nullable' => true,
                            'precision' => 0,
                            'columnName' => 'fecha',
                        ],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'juego' => 'juego',
                        'hashtag' => 'hashtag',
                        'url' => 'url',
                        'texto' => 'texto',
                        'imagen' => 'imagen',
                        'video' => 'video',
                        'usuario' => 'usuario',
                        'foto_usuario' => 'fotoUsuario',
                        'contgamepre' => 'contgamepre',
                        'contgamepost' => 'contgamepost',
                        'id_tweet' => 'idTweet',
                        'fecha' => 'fecha',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'juego' => 'juego',
                        'hashtag' => 'hashtag',
                        'url' => 'url',
                        'texto' => 'texto',
                        'imagen' => 'imagen',
                        'video' => 'video',
                        'usuario' => 'usuario',
                        'fotoUsuario' => 'foto_usuario',
                        'contgamepre' => 'contgamepre',
                        'contgamepost' => 'contgamepost',
                        'idTweet' => 'id_tweet',
                        'fecha' => 'fecha',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'tweet',
                    ],
                ],
                'idGenerator' => [
                    $o[1],
                ],
            ],
        ],
        $o[0],
        []
    );
},
3 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Id\\AssignedGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\AssignedGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'App\\Entity\\TweetGuardado',
                ],
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\TweetGuardado',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\TweetGuardadoRepository',
                ],
                'identifier' => [
                    [
                        'idTweet',
                        'idUser',
                    ],
                ],
                'fieldMappings' => [
                    [
                        'id' => [
                            'fieldName' => 'id',
                            'type' => 'integer',
                            'scale' => 0,
                            'length' => null,
                            'unique' => false,
                            'nullable' => true,
                            'precision' => 0,
                            'columnName' => 'id',
                        ],
                        'idTweet' => [
                            'fieldName' => 'idTweet',
                            'type' => 'string',
                            'scale' => 0,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'id' => true,
                            'columnName' => 'id_tweet',
                        ],
                        'idUser' => [
                            'fieldName' => 'idUser',
                            'type' => 'integer',
                            'scale' => 0,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'id' => true,
                            'columnName' => 'id_user',
                        ],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'id_tweet' => 'idTweet',
                        'id_user' => 'idUser',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'idTweet' => 'id_tweet',
                        'idUser' => 'id_user',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'tweet_guardado',
                    ],
                ],
                'isIdentifierComposite' => [
                    true,
                ],
                'idGenerator' => [
                    $o[1],
                ],
            ],
        ],
        $o[0],
        []
    );
},
4 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'App\\Entity\\User',
                ],
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\User',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\UserRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => [
                            'fieldName' => 'id',
                            'type' => 'integer',
                            'scale' => 0,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'id' => true,
                            'columnName' => 'id',
                        ],
                        'username' => [
                            'fieldName' => 'username',
                            'type' => 'string',
                            'scale' => 0,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'username',
                        ],
                        'email' => [
                            'fieldName' => 'email',
                            'type' => 'string',
                            'scale' => 0,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'email',
                        ],
                        'password' => [
                            'fieldName' => 'password',
                            'type' => 'string',
                            'scale' => 0,
                            'length' => 64,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'password',
                        ],
                        'roles' => [
                            'fieldName' => 'roles',
                            'type' => 'simple_array',
                            'scale' => 0,
                            'length' => null,
                            'unique' => false,
                            'nullable' => true,
                            'precision' => 0,
                            'columnName' => 'roles',
                        ],
                        'isActive' => [
                            'fieldName' => 'isActive',
                            'type' => 'boolean',
                            'scale' => 0,
                            'length' => null,
                            'unique' => false,
                            'nullable' => true,
                            'precision' => 0,
                            'columnName' => 'is_active',
                        ],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'username' => 'username',
                        'email' => 'email',
                        'password' => 'password',
                        'roles' => 'roles',
                        'is_active' => 'isActive',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'username' => 'username',
                        'email' => 'email',
                        'password' => 'password',
                        'roles' => 'roles',
                        'isActive' => 'is_active',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'user',
                    ],
                ],
                'idGenerator' => [
                    $o[1],
                ],
            ],
        ],
        $o[0],
        []
    );
},

]];
