<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDZmfh40\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDZmfh40/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerDZmfh40.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerDZmfh40\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerDZmfh40\App_KernelProdContainer([
    'container.build_hash' => 'DZmfh40',
    'container.build_id' => '04369d92',
    'container.build_time' => 1621610724,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDZmfh40');
