<?php

namespace ContainerDZmfh40;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGuiltyControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\GuiltyController' shared autowired service.
     *
     * @return \App\Controller\GuiltyController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\GuiltyController'] = $instance = new \App\Controller\GuiltyController();

        $instance->setContainer(($container->privates['.service_locator.5nX7ca3'] ?? $container->load('get_ServiceLocator_5nX7ca3Service'))->withContext('App\\Controller\\GuiltyController', $container));

        return $instance;
    }
}
