<?php

namespace ContainerDZmfh40;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPersonajeRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\PersonajeRepository' shared autowired service.
     *
     * @return \App\Repository\PersonajeRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\PersonajeRepository'] = new \App\Repository\PersonajeRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
