<?php

namespace ContainerDZmfh40;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTweetGuardadoRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\TweetGuardadoRepository' shared autowired service.
     *
     * @return \App\Repository\TweetGuardadoRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\TweetGuardadoRepository'] = new \App\Repository\TweetGuardadoRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
