<?php

namespace ContainerDZmfh40;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTweetRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\TweetRepository' shared autowired service.
     *
     * @return \App\Repository\TweetRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\TweetRepository'] = new \App\Repository\TweetRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
