<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Personaje extends \App\Entity\Personaje implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Personaje' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Personaje' . "\0" . 'juego', '' . "\0" . 'App\\Entity\\Personaje' . "\0" . 'nombre', '' . "\0" . 'App\\Entity\\Personaje' . "\0" . 'nombreCompleto', '' . "\0" . 'App\\Entity\\Personaje' . "\0" . 'hashtag', '' . "\0" . 'App\\Entity\\Personaje' . "\0" . 'dificultad', '' . "\0" . 'App\\Entity\\Personaje' . "\0" . 'descripcionHeader', '' . "\0" . 'App\\Entity\\Personaje' . "\0" . 'descripcionBody', '' . "\0" . 'App\\Entity\\Personaje' . "\0" . 'discord'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Personaje' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Personaje' . "\0" . 'juego', '' . "\0" . 'App\\Entity\\Personaje' . "\0" . 'nombre', '' . "\0" . 'App\\Entity\\Personaje' . "\0" . 'nombreCompleto', '' . "\0" . 'App\\Entity\\Personaje' . "\0" . 'hashtag', '' . "\0" . 'App\\Entity\\Personaje' . "\0" . 'dificultad', '' . "\0" . 'App\\Entity\\Personaje' . "\0" . 'descripcionHeader', '' . "\0" . 'App\\Entity\\Personaje' . "\0" . 'descripcionBody', '' . "\0" . 'App\\Entity\\Personaje' . "\0" . 'discord'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Personaje $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getJuego(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJuego', []);

        return parent::getJuego();
    }

    /**
     * {@inheritDoc}
     */
    public function setJuego(string $juego): \App\Entity\Personaje
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJuego', [$juego]);

        return parent::setJuego($juego);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', []);

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre(string $nombre): \App\Entity\Personaje
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', [$nombre]);

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombreCompleto(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombreCompleto', []);

        return parent::getNombreCompleto();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombreCompleto(string $nombreCompleto): \App\Entity\Personaje
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombreCompleto', [$nombreCompleto]);

        return parent::setNombreCompleto($nombreCompleto);
    }

    /**
     * {@inheritDoc}
     */
    public function getHashtag(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHashtag', []);

        return parent::getHashtag();
    }

    /**
     * {@inheritDoc}
     */
    public function setHashtag(string $hashtag): \App\Entity\Personaje
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHashtag', [$hashtag]);

        return parent::setHashtag($hashtag);
    }

    /**
     * {@inheritDoc}
     */
    public function getDificultad(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDificultad', []);

        return parent::getDificultad();
    }

    /**
     * {@inheritDoc}
     */
    public function setDificultad(int $dificultad): \App\Entity\Personaje
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDificultad', [$dificultad]);

        return parent::setDificultad($dificultad);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcionHeader(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcionHeader', []);

        return parent::getDescripcionHeader();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcionHeader(?string $descripcionHeader): \App\Entity\Personaje
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcionHeader', [$descripcionHeader]);

        return parent::setDescripcionHeader($descripcionHeader);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcionBody(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcionBody', []);

        return parent::getDescripcionBody();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcionBody(?string $descripcionBody): \App\Entity\Personaje
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcionBody', [$descripcionBody]);

        return parent::setDescripcionBody($descripcionBody);
    }

    /**
     * {@inheritDoc}
     */
    public function getDiscord(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDiscord', []);

        return parent::getDiscord();
    }

    /**
     * {@inheritDoc}
     */
    public function setDiscord(?string $discord): \App\Entity\Personaje
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDiscord', [$discord]);

        return parent::setDiscord($discord);
    }

}
