<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Tweet extends \App\Entity\Tweet implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
  'juego' => NULL,
  'hashtag' => NULL,
  'url' => NULL,
  'texto' => NULL,
  'imagen' => NULL,
  'video' => NULL,
  'usuario' => NULL,
  'fotoUsuario' => NULL,
  'contgamepre' => NULL,
  'contgamepost' => NULL,
  'idTweet' => NULL,
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
  'juego' => NULL,
  'hashtag' => NULL,
  'url' => NULL,
  'texto' => NULL,
  'imagen' => NULL,
  'video' => NULL,
  'usuario' => NULL,
  'fotoUsuario' => NULL,
  'contgamepre' => NULL,
  'contgamepost' => NULL,
  'idTweet' => NULL,
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {
        unset($this->juego, $this->hashtag, $this->url, $this->texto, $this->imagen, $this->video, $this->usuario, $this->fotoUsuario, $this->contgamepre, $this->contgamepost, $this->idTweet);

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }

    /**
     * 
     * @param string $name
     */
    public function __get($name)
    {
        if (\array_key_exists($name, self::$lazyPropertiesNames)) {
            $this->__initializer__ && $this->__initializer__->__invoke($this, '__get', [$name]);
            return $this->$name;
        }

        trigger_error(sprintf('Undefined property: %s::$%s', __CLASS__, $name), E_USER_NOTICE);

    }

    /**
     * 
     * @param string $name
     * @param mixed  $value
     */
    public function __set($name, $value)
    {
        if (\array_key_exists($name, self::$lazyPropertiesNames)) {
            $this->__initializer__ && $this->__initializer__->__invoke($this, '__set', [$name, $value]);

            $this->$name = $value;

            return;
        }

        $this->$name = $value;
    }

    /**
     * 
     * @param  string $name
     * @return boolean
     */
    public function __isset($name)
    {
        if (\array_key_exists($name, self::$lazyPropertiesNames)) {
            $this->__initializer__ && $this->__initializer__->__invoke($this, '__isset', [$name]);

            return isset($this->$name);
        }

        return false;
    }

    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'id', 'juego', 'hashtag', 'url', 'texto', 'imagen', 'video', 'usuario', 'fotoUsuario', 'contgamepre', 'contgamepost', 'idTweet', '' . "\0" . 'App\\Entity\\Tweet' . "\0" . 'fecha'];
        }

        return ['__isInitialized__', 'id', '' . "\0" . 'App\\Entity\\Tweet' . "\0" . 'fecha'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Tweet $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

            unset($this->juego, $this->hashtag, $this->url, $this->texto, $this->imagen, $this->video, $this->usuario, $this->fotoUsuario, $this->contgamepre, $this->contgamepost, $this->idTweet);
        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getJuego(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJuego', []);

        return parent::getJuego();
    }

    /**
     * {@inheritDoc}
     */
    public function setJuego(string $juego): \App\Entity\Tweet
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJuego', [$juego]);

        return parent::setJuego($juego);
    }

    /**
     * {@inheritDoc}
     */
    public function getHashtag(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHashtag', []);

        return parent::getHashtag();
    }

    /**
     * {@inheritDoc}
     */
    public function setHashtag(string $hashtag): \App\Entity\Tweet
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHashtag', [$hashtag]);

        return parent::setHashtag($hashtag);
    }

    /**
     * {@inheritDoc}
     */
    public function getUrl(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUrl', []);

        return parent::getUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function setUrl(string $url): \App\Entity\Tweet
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUrl', [$url]);

        return parent::setUrl($url);
    }

    /**
     * {@inheritDoc}
     */
    public function getTexto(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTexto', []);

        return parent::getTexto();
    }

    /**
     * {@inheritDoc}
     */
    public function setTexto(?string $texto): \App\Entity\Tweet
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTexto', [$texto]);

        return parent::setTexto($texto);
    }

    /**
     * {@inheritDoc}
     */
    public function getImagen(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImagen', []);

        return parent::getImagen();
    }

    /**
     * {@inheritDoc}
     */
    public function setImagen(?string $imagen): \App\Entity\Tweet
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImagen', [$imagen]);

        return parent::setImagen($imagen);
    }

    /**
     * {@inheritDoc}
     */
    public function getVideo(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVideo', []);

        return parent::getVideo();
    }

    /**
     * {@inheritDoc}
     */
    public function setVideo(?string $video): \App\Entity\Tweet
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVideo', [$video]);

        return parent::setVideo($video);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuario(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuario', []);

        return parent::getUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuario(string $usuario): \App\Entity\Tweet
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuario', [$usuario]);

        return parent::setUsuario($usuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getFotoUsuario(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFotoUsuario', []);

        return parent::getFotoUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setFotoUsuario(?string $fotoUsuario): \App\Entity\Tweet
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFotoUsuario', [$fotoUsuario]);

        return parent::setFotoUsuario($fotoUsuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getContgamepre(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContgamepre', []);

        return parent::getContgamepre();
    }

    /**
     * {@inheritDoc}
     */
    public function setContgamepre(int $contgamepre): \App\Entity\Tweet
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContgamepre', [$contgamepre]);

        return parent::setContgamepre($contgamepre);
    }

    /**
     * {@inheritDoc}
     */
    public function getContgamepost(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContgamepost', []);

        return parent::getContgamepost();
    }

    /**
     * {@inheritDoc}
     */
    public function setContgamepost(int $contgamepost): \App\Entity\Tweet
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContgamepost', [$contgamepost]);

        return parent::setContgamepost($contgamepost);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdTweet(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdTweet', []);

        return parent::getIdTweet();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdTweet(int $idTweet): \App\Entity\Tweet
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdTweet', [$idTweet]);

        return parent::setIdTweet($idTweet);
    }

    /**
     * {@inheritDoc}
     */
    public function getFecha(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFecha', []);

        return parent::getFecha();
    }

    /**
     * {@inheritDoc}
     */
    public function setFecha(?\DateTimeInterface $fecha): \App\Entity\Tweet
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFecha', [$fecha]);

        return parent::setFecha($fecha);
    }

}
